version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/src/node-app"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/src/python-app"
    schedule:
      interval: "weekly"