name: CI Python
on:
  push:
    paths:
      - ".github/workflows/ci-python.yml"
      - "src/python-app/**"
  pull_request:
    paths:
      - ".github/workflows/ci-python.yml"
      - "src/python-app/**"
concurrency:
  group: ci-python-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('src/python-app/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ runner.os }}-pip-
      - name: Install deps
        working-directory: src/python-app
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install pytest pytest-cov; fi
      - name: Run tests
        working-directory: src/python-app
        run: |
          pytest -q --cov=./ --cov-report=xml --junitxml=pytest.xml
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: python-${{ matrix.python-version }}-reports
          path: |
            src/python-app/coverage.xml
            src/python-app/pytest.xml