name: Docker build and publish (GHCR) + optional deploy

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Optional additional image tag"
        required: false
        type: string

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract tags
        id: meta
        run: |
          TAGS="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sha-${GITHUB_SHA::7}"
          if [ -n "${{ github.ref_type == 'tag' && github.ref_name || '' }}" ]; then
            TAGS="$TAGS,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}"
          fi
          if [ -n "${{ inputs.image_tag }}" ]; then
            TAGS="$TAGS,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.image_tag }}"
          fi
          echo "tags=$TAGS" >> "$GITHUB_OUTPUT"
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          provenance: false

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://example.invalid # replace with your real URL after deploy
    steps:
      - name: Prepare deploy
        run: |
          echo "Deploying image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
      # Place real deployment steps here (e.g., kubectl, ssh, cloud CLI)
      # This job will wait for approval if environment 'production' has reviewers configured.